# Generated by Django 3.0.5 on 2023-12-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_src',
            field=models.CharField(default='https://dbdzm869oupei.cloudfront.net/img/posters/preview/91008.png', max_length=255),
        ),
    ]
